# Generated by Django 3.2.7 on 2021-09-23 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madel',
            name='mark',
        ),
        migrations.AddField(
            model_name='madel',
            name='marks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.mark'),
        ),
    ]
