# Generated by Django 3.2.7 on 2021-09-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210923_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='ads',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cars.ads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='madel',
            name='marks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.mark'),
        ),
    ]
