# Generated by Django 3.2.7 on 2021-09-24 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_auto_20210923_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'ordering': ['-id'], 'verbose_name': 'Реклама', 'verbose_name_plural': 'Рекламы'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-id'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['-id'], 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цветы'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'Комментария', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='madel',
            options={'ordering': ['-id'], 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['-id'], 'verbose_name': 'Марка', 'verbose_name_plural': 'Марки'},
        ),
        migrations.AlterField(
            model_name='ads',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Называния рекламы'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='madel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.madel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.mark', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.ads', verbose_name='Реклама'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Коментарии'),
        ),
        migrations.AlterField(
            model_name='madel',
            name='marks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.mark', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='madel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Марка'),
        ),
    ]
